apiVersion: apps/v1
kind: Deployment
metadata:
  name: ivy-stack
spec:
  replicas: {{ .Values.ivy.replicaCount }}
  selector:
    matchLabels:
      {{- include "ivy-stack.selectorLabels" . | nindent 6 }}   {{/* ③ ivy-stack.selectorLabels */}}
  template:
    metadata:
      labels:
        {{- include "ivy-stack.selectorLabels" . | nindent 8 }}  {{/* ③ ivy-stack.selectorLabels */}}
    spec:
      containers:
        - name: ivy
          image: "{{ .Values.ivy.image.repository }}:{{ .Values.ivy.image.tag }}"
          imagePullPolicy: {{ .Values.ivy.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.ivy.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /system/health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /system/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          env:
            - name: ivy_Administrators_admin_Password
              valueFrom:
                secretKeyRef:
                  name: ivy12-ivy-secret
                  key: admin-password
            - name: ivy_SystemDb_Url
              value: "jdbc:sqlserver://{{ .Release.Name }}-mssql:1433;databaseName={{ .Values.ivy.db.name }}"
            - name: ivy_SystemDb_UserName
              value: {{ .Values.ivy.db.user }}
            - name: ivy_SystemDb_Password
              valueFrom:
                secretKeyRef:
                  name: ivy12-mssql-secret
                  key: sapassword
            - name: ivy_SearchEngine_ExternalServer_Url
              value: "http://{{ .Release.Name }}-opensearch-cluster-master:{{ .Values.ivy.search.port }}"
          volumeMounts:
            - name: config-volume
              mountPath: /ivy/configuration
            - name: ivy-data
              mountPath: /ivy/data
            - name: ivy-applications
              mountPath: /ivy/applications
          resources:
            {{- toYaml .Values.ivy.resources | nindent 12 }}
      volumes:
        - name: ivy-data
          persistentVolumeClaim:
            claimName: {{ include "ivy-stack.ivy.fullname" . }}-data          {{/* ① ivy-stack.ivy.fullname */}}
        - name: ivy-applications
          persistentVolumeClaim:
            claimName: {{ include "ivy-stack.ivy.fullname" . }}-applications  {{/* ① ivy-stack.ivy.fullname */}}
        - name: config-volume
          configMap:
            name: {{ include "ivy-stack.ivy.fullname" . }}-config              {{/* ① ivy-stack.ivy.fullname */}}
            items:
              - key: LICENCE
                path: licence.lic
              - key: JGROUPS
                path: jgroups.xml
              - key: LOG4J2
                path: log4j2.xml
