apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ivy-stack.ivy.fullname" . }}-data     {{/* ① ivy-stack.ivy.fullname */}}
  labels:
    {{- include "ivy-stack.labels" . | nindent 4 }}        {{/* ② ivy-stack.labels */}}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.ivy.persistence.data.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ivy-stack.ivy.fullname" . }}-applications   {{/* ① ivy-stack.ivy.fullname */}}
  labels:
    {{- include "ivy-stack.labels" . | nindent 4 }}              {{/* ② ivy-stack.labels */}}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.ivy.persistence.applications.size }}
