apiVersion: v1
kind: Secret
metadata:
  name: ivy12-ivy-secret
  namespace: ivy12
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  admin-password: "admin"
---
apiVersion: v1
kind: Secret
metadata:
  name: ivy12-opensearch-secret
  namespace: ivy12
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  admin-password: "CHANGEME"
